---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/gtpare02/public_html/AmigosdaFe
    - /bin/cp -R ./IMG $DEPLOYPATH/
    - /bin/cp ./style.css $DEPLOYPATH/
    - /bin/cp ./script.js $DEPLOYPATH/
    - /bin/cp ./index.html $DEPLOYPATH/
    - /bin/cp ./atividades.html $DEPLOYPATH/
    - /bin/cp ./atividades.css $DEPLOYPATH/
